name: Build & Create Release for Raspberry Pi
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        run: npm run build

      - name: Create standalone build
        run: |
          mv .next/standalone ./dist
          cp -r .next/static ./dist/.next/
          cp -r public ./dist/

      - name: Package release
        run: tar -czf release.tar.gz dist/

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: release.tar.gz
          name: ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}

            To deploy on your Raspberry Pi:
            1. Extract the release:
               ```bash
               tar xzf release.tar.gz
               cd dist
               ```
            2. Install dependencies:
               ```bash
               npm install
               ```
            3. Start the server:
               ```bash
               node server.js
               ```

            Requirements:
            - Node.js 18 or later
          draft: false
          prerelease: false
