# .github/workflows/build-release.yml
name: Build & Create Multi-Platform Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-raspberry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        run: npm run build

      - name: Create standalone build
        run: |
          mv .next/standalone ./dist-raspberry
          cp -r .next/static ./dist-raspberry/.next/
          cp -r public ./dist-raspberry/

      - name: Package Raspberry Pi release
        run: tar -czf system-stats-raspberry.tar.gz dist-raspberry/

      - name: Upload Raspberry Pi artifact
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-build
          path: system-stats-raspberry.tar.gz

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        run: npm run build

      - name: Create standalone build
        run: |
          mv .next/standalone ./dist-ubuntu
          cp -r .next/static ./dist-ubuntu/.next/
          cp -r public ./dist-ubuntu/

      - name: Package Ubuntu release
        run: tar -czf system-stats-ubuntu.tar.gz dist-ubuntu/

      - name: Upload Ubuntu artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-build
          path: system-stats-ubuntu.tar.gz

  create-release:
    needs: [build-raspberry, build-ubuntu]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download Raspberry Pi artifact
        uses: actions/download-artifact@v4
        with:
          name: raspberry-build

      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            system-stats-raspberry.tar.gz
            system-stats-ubuntu.tar.gz
          name: ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}

            ## Raspberry Pi Installation
            To deploy on your Raspberry Pi:
            1. Extract the release:
               ```bash
               tar xzf system-stats-raspberry.tar.gz
               cd dist-raspberry
               ```
            2. Install dependencies:
               ```bash
               npm install
               ```
            3. Start the server:
               ```bash
               node server.js
               ```

            ## Ubuntu Installation
            To deploy on Ubuntu:
            1. Extract the release:
               ```bash
               tar xzf system-stats-ubuntu.tar.gz
               cd dist-ubuntu
               ```
            2. Install dependencies:
               ```bash
               npm install
               ```
            3. Start the server:
               ```bash
               node server.js
               ```

            Requirements:
            - Node.js 18 or later
          draft: false
          prerelease: false
